server:
    port: 9000

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/blog
        username: root
        password: root
    hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        packages_to_scan: hello
